### ISSUE TITLE
[BUG] crash when getting teleported into the TARDIS

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#107]
Your mod and the dalek mod don't really play nice do they

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 14-5-15 14:40
Description: Exception ticking world entities

java.lang.IndexOutOfBoundsException: Index: 209, Size: 209
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at net.minecraft.world.World.func_72939_s(World.java:1920)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This happened when i got out and got shot by a dalek, and thus got teleported back in.

**Comment by DarkholmeTenk** [comment]
Nothing helpful that I can see; have you managed to replicate it? I reckon it's the dalek trying to play a sound or something after the world's already started to unload and crashing because of it.

**Comment by FoxPotato** [comment]
It's not that hard to recreate. It happened everytime I left the TARDIS lmao.
I just uninstalled the dalek mod. It didn't add anything of interest anyway.

**Comment by DarkholmeTenk** [comment]
Did you add the Dalek mod after creating your first TARDIS? It could be that the Dalek Mod has registered a dimension to the same dimension as a TARDIS

**Comment by FoxPotato** [comment]
No I added them at the same time. Well I added the dalek later but the world was created with them both

**Comment by DarkholmeTenk** [comment]
On consideration, I think it's caused by asynchronous teleportation. I.e. the code which does the transmat is called from a hurt event which means it's running in a separate thread to the rest of the world. So the hurt event teleport is taking place while the rest of the world's still trying to do stuff, resulting in a crash.
