### ISSUE TITLE
[BUG] Transmat-Crash when transmating enderdragon

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#206]
i landed in the twilight forrest next to a naga and wondered.... what would happen if i trans mat it into the tardis? figuring it would crash me i went to a creative world and sure enough when i hit the dragon boom! instant crash. i take it this one is simple enough to reproduce that a crash report is unnessisary?

**Comment by DarkholmeTenk** [comment]
Well you uploading the crash report would be quicker tbh

**Comment by AlienXtream** [comment]
Well really all you need to do is blacklist all boss mob entities. I tried it with he naga and it crashed too. There is a property on the bosses that you can check for right?

**Comment by PrincessOfEvil** [comment]
Can you just post the log already?

2015-06-21 10:40 GMT+06:00 AlienXtream notifications@github.com:

**Comment by AlienXtream** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 19/06/15 6:14 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:562)
    at net.minecraft.server.management.ServerConfigurationManager.func_82448_a(ServerConfigurationManager.java:509)
    at io.darkcraft.darkcore.mod.helpers.TeleportHelper.transferEntityToDimension(TeleportHelper.java:42)
    at io.darkcraft.darkcore.mod.helpers.TeleportHelper.teleportEntity(TeleportHelper.java:65)
    at tardis.common.tileents.CoreTileEntity.transmatEntity(CoreTileEntity.java:1290)
    at tardis.common.items.SonicScrewdriverItem.func_77644_a(SonicScrewdriverItem.java:492)
    at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:299)
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1282)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:562)
    at net.minecraft.server.management.ServerConfigurationManager.func_82448_a(ServerConfigurationManager.java:509)
    at io.darkcraft.darkcore.mod.helpers.TeleportHelper.transferEntityToDimension(TeleportHelper.java:42)
    at io.darkcraft.darkcore.mod.helpers.TeleportHelper.teleportEntity(TeleportHelper.java:65)
    at tardis.common.tileents.CoreTileEntity.transmatEntity(CoreTileEntity.java:1290)
    at tardis.common.items.SonicScrewdriverItem.func_77644_a(SonicScrewdriverItem.java:492)
    at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:299)
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1282)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@4c09d02e
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
