### ISSUE TITLE
[CRASH] Cant load mod

### ISSUE THREAD

**Issue by McDrakon123** [DarkholmeTenk/TardisModIssues#212]
Here is the crash report:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 29/06/15 16:15
Description: Initializing game

net.minecraftforge.client.model.ModelFormatException: Error parsing entry ('o Cube_Cube.001', line 3) in file 'tardismod:models/screen.obj' - Incorrect format
    at net.minecraftforge.client.model.obj.WavefrontObject.parseGroupObject(WavefrontObject.java:511)
    at net.minecraftforge.client.model.obj.WavefrontObject.loadObjModel(WavefrontObject.java:131)
    at net.minecraftforge.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:56)
    at net.minecraftforge.client.model.obj.ObjModelLoader.loadInstance(ObjModelLoader.java:27)
    at net.minecraftforge.client.model.AdvancedModelLoader.loadModel(AdvancedModelLoader.java:65)
    at tardis.client.renderer.tileents.CoreRenderer.<init>(CoreRenderer.java:38)
    at tardis.client.TardisClientProxy.postAssignment(TardisClientProxy.java:80)
    at tardis.TardisMod.preInit(TardisMod.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraftforge.client.model.obj.WavefrontObject.parseGroupObject(WavefrontObject.java:511)
    at net.minecraftforge.client.model.obj.WavefrontObject.loadObjModel(WavefrontObject.java:131)
    at net.minecraftforge.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:56)
    at net.minecraftforge.client.model.obj.ObjModelLoader.loadInstance(ObjModelLoader.java:27)
    at net.minecraftforge.client.model.AdvancedModelLoader.loadModel(AdvancedModelLoader.java:65)
    at tardis.client.renderer.tileents.CoreRenderer.<init>(CoreRenderer.java:38)
    at tardis.client.TardisClientProxy.postAssignment(TardisClientProxy.java:80)
    at tardis.TardisMod.preInit(TardisMod.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 119592136 bytes (114 MB) / 270561280 bytes (258 MB) up to 3207856128 bytes (3059 MB)
    Mod Pack: ~~ERROR~~ NullPointerException: null
    LiteLoader Mods: ~~ERROR~~ NullPointerException: null
    LaunchWrapper: 26 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.thevoxelbox.voxelmenu.SlotTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.renderdecorator.asm.RenderPlayerTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmenu.PanoramaTransformer
          - Transformer: net.eq2online.macros.transformers.MacrosTransformer
          - Transformer: net.eq2online.macros.transformers.CollectionPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 11 mods loaded, 11 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized
    CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized
    darkcore{0.25} [Dark Core](darkcore-0.25-30.jar) Unloaded->Constructed->Pre-initialized
    FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized
    mineTunes{1.1-5} [mineTunes](MineTunes 1.1-5.jar) Unloaded->Constructed->Pre-initialized
    RWG{Alpha 1.3.2} [Realistic World Gen Alpha](RWG-alpha-1.3.2.jar) Unloaded->Constructed->Pre-initialized
    TardisMod{0.985} [Tardis Mod](tardismod-1.7.10-0.985-150.jar) Unloaded->Constructed->Errored
    CoFHCore: -[1.7.10]3.0.2-262
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.3347, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by DarkholmeTenk** [comment]
Not certain, but I'm pretty sure this is a forge bug.
Try updating forge to the latest/recommended 1.7.10 version.

**Comment by McDrakon123** [comment]
Ok i updated, now....

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 30/06/15 17:41
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: cofh/api/tileentity/IReconfigurableFacing
    at tardis.common.items.SonicScrewdriverItem.rightClickBlock(SonicScrewdriverItem.java:332)
    at tardis.common.items.SonicScrewdriverItem.func_77659_a(SonicScrewdriverItem.java:475)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: cofh.api.tileentity.IReconfigurableFacing
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 16 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 225019512 bytes (214 MB) / 392667136 bytes (374 MB) up to 3207856128 bytes (3059 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 5 loaded mod(s)
          - Macro / Keybind Mod version 0.10.12
          - VoxelMenu version 4.1.4
          - RenderDecorator version 1.1.1
          - VoxelLib version 2.3.1
          - VoxelMenu Music version 12.0
    LaunchWrapper: 25 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.thevoxelbox.voxelmenu.SlotTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.renderdecorator.asm.RenderPlayerTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmenu.PanoramaTransformer
          - Transformer: net.eq2online.macros.transformers.MacrosTransformer
          - Transformer: net.eq2online.macros.transformers.CollectionPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   darkcore{0.25} [Dark Core](darkcore-0.25-30 %281%29.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   mineTunes{1.1-5} [mineTunes](MineTunes 1.1-5.jar) 
    UCHIJAAAA   TardisMod{0.985} [Tardis Mod](tardismod-1.7.10-0.985-150 %281%29.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['DRedDog'/0, l='TARDIS', x=1.94, y=68.00, z=9.49]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by FoxPotato** [comment]
Do you have cofhcore installed?

**Comment by McDrakon123** [comment]
no

**Comment by McDrakon123** [comment]
also, could you update http://tardismod.com/ cause i cant find the ext scanner

**Comment by McDrakon123** [comment]
also what are the buttons under neath the control panel for...

**Comment by McDrakon123** [comment]
1 more question. How does the tardis gain xp

**Comment by McDrakon123** [comment]
nvmm

**Comment by FoxPotato** [comment]
the website will get updated at some point, the external scanner is gained once you reach level 5. And you earn xp by flying the TARDIS correctly. Also, please try to edit messages instead of making alot of small ones. :)

**Comment by DarkholmeTenk** [comment]
Install the latest version of TardisMod and DarkCore from the jenkins and that'll fix your CoFHCore crash. Use the manual in the library room to find stuff.

**Comment by McDrakon123** [comment]
The manual doesnt say what the things under the console are used for, ive worked out that one is permissions and another is for permissions on a screwdriver, but recall doesnt seem to work.

**Comment by Soyaro666** [comment]
the screwdriver features are unlocked on higher tardis levels like most features.
my suggestion: set speed on lowest above 0, activate uncoordinated flight mode, take off and keep on using every glowing lever and button until your tardis reaches at least level 10
