### ISSUE TITLE
Error when trying to load a new consoleroom

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#221]
I created my own console room, when I try this the log shows the following error:

[05:39:42] [Server thread/INFO] [STDOUT/]: [io.darkcraft.darkcore.mod.helpers.TeleportHelper:teleportEntity:75]: [TTH]Teleport request: 6 > 13.5,69.0,0.5
[05:39:42] [Server thread/DEBUG] [NotEnoughItems/]: Sending serverside check to: Katorone
[05:39:43] [Server thread/INFO] [JourneyMapServer/]: On Request: Sending WorldID packet to: Katorone
[05:39:43] [Server thread/INFO] [JourneyMapServer/]: Katorone is an EntityPlayerMP attempting to send the worldId packet
[05:40:02] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:73
[05:40:03] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:73
[05:40:03] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TH]Loading diff from file
[05:40:03] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TPB]Name is a diff, so setting to tardisConsoleFull
[05:40:03] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TH]TimeTaken (ms):2
[05:40:05] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:72
[05:40:05] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:72
[05:40:07] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:73
[05:40:08] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:73
[05:40:08] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TH]USE:false:true:true | tardisConsoleKato<-tardisConsoleFull
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: tardis.common.core.exception.schema.UnmatchingSchemaException: USE:false:true:true | tardisConsoleKato<-tardisConsoleFull
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.core.schema.PartBlueprint.<init>(PartBlueprint.java:380)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.core.Helper.loadSchemaDiff(Helper.java:281)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.tileents.CoreTileEntity.loadConsoleRoom(CoreTileEntity.java:961)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.tileents.EngineTileEntity.activateControl(EngineTileEntity.java:371)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.network.packet.ControlPacketHandler.handleData(ControlPacketHandler.java:35)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomPacket(PacketHandler.java:41)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomServerPacket(PacketHandler.java:28)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler_603_PacketHandler_handleCustomServerPacket_ServerCustomPacketEvent.invoke(.dynamic)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05:40:08] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[05:40:08] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TH]TimeTaken (ms):3

The schema & TardisIDS.dat : http://midgard.laerad.net/infinityplus/tardisBugReport/tardisbugreport.tar.gz
There are blocks being used from Railcraft, Tinkers' Construct and Extra Utilities.

Versions used:
tardismod-1.7.10-0.985-182
darkcore-0.25-36

**Comment by FoxPotato** [comment]
Do you have the latest version of all mods? Especially darkcore?
http://darkhol.me:8080/job/Darkcore/
http://darkhol.me:8080/job/TardisMod/

**Comment by ghost** [comment]
I was using:
tardismod-1.7.10-0.985-182
darkcore-0.25-36

I'll test with tardismod-1.7.10-0.985-183 now.

Update:  The problem persists with the exact same error.

**Comment by FoxPotato** [comment]
does this error occur with every console? Did you place a block where the engine or console should be? Have you tried removing mod blocks and seeing if the error still occurs? maybe only removing the mod blocks from 1 mod to see which one causes it.

**Comment by ghost** [comment]
I can switch between the premade and a simple custom made console without issues.
The entire area around the console, engine and the part on top is clear of blocks.

The weird thing is that I can spawn in the schema manually without problems.
I'll try replacing the structural blocks with standard tardis blocks and see what happens.  (Hurray for worldedit)

**Comment by ghost** [comment]
I've switched out all mod blocks with tardis blocks and saved under a new room.
I then did /treload to refresh the schema's and tried loading the console.
The same error persists.

The console room without custom blocks: http://midgard.laerad.net/infinityplus/tardisBugReport/tardisConsoleKatoClean.schema

Some things that might be messing things up, and I'm unsure about:
I started with this build loading in a 2nd console room in a taris world, then building around it.  The console, engine an rotor are invisible blocks.
I placed the tardis door manually (but it's placed on the edge of the boundaries)

**Comment by FoxPotato** [comment]
don't place the TARDIS door yourself. The TARDIS places the timerotor, console and engine automatically. the invisible blocks are just to show where you can't build :p

**Comment by ghost** [comment]
I've removed the door on the schema without mod blocks, and did /treload.  The error persists however.

**Comment by FoxPotato** [comment]
did you build outside of the schematic boundaries? did you change the room size, or build anything outside at all?

**Comment by ghost** [comment]
I made the room a lot larger (45x38x45), but adjusted the schema boundaries to contain the entire building.  There's nothing but space and the main tardis control room outside.

**Comment by FoxPotato** [comment]
You can't adjust the size of the console room. I think we found your problem :p

**Comment by ghost** [comment]
Ah.  Guess now we know. :)
Is there a practical reason why the size can't be adjusted?

**Comment by FoxPotato** [comment]
It's because of coordinates, entering the TARDIS places you at specific coords. :)

**Comment by ghost** [comment]
Guess I'll cut out a part of the build, make that the new control room, and create some components that'd fit around it.
Thanks for your help!

**Comment by DarkholmeTenk** [comment]
As a note, if you don't care that the door will place you in the wrong place, you can overwrite tardisConsoleMain and newly generated tardises will use the new schematics and you won't be able to switch back to the old size :P

**Comment by ghost** [comment]
I wouldn't want to force that room on others playing on the server.  Could the addition of a "spawn here block" solve the problem perhaps?

**Comment by FoxPotato** [comment]
Did making the room smaller fix the error?
And that probably wouldn't help, the spawn block, the way this works is; it doesn't replace the original room exactly. it basically add and removes the differences. Thats why editing the default console would work :p

**Comment by DarkholmeTenk** [comment]
I could use the door; the problem is it adds a search time to every teleport into the tardis :P

**Comment by ghost** [comment]
Haven't been able yet to try a smaller design.  But a previous design worked perfectly, so I'm convinced it'll work.  I need to think for a bit how to link the different parts together so they fit nicely around the console room.  The schema boundaries complicate things. :)

Increased search time wouldn't really be an issue for me.  If the search starts at the door, it shouldn't take any longer than it does now?

Working with the differences is really smart.  I should have realized it adds a layer of complexity that makes differences in size hard to solve.

**Comment by ghost** [comment]
I've cut out a piece of the design with the modded blocks and set this as the console room.  This works.
My problem seems solved.  Feel free to close this. :-)

Thanks!

**Comment by ghost** [comment]
Just a small remark though, when I set this as the consoleroom, the tardis did not automatically create the door.

**Comment by DarkholmeTenk** [comment]
Asin the door to the outside or the door further inside?
Both of these are actually part of the schematic; the console and tile entities are all generated automatically though.

Working with the differences was the only way I could get the time to switch to a reasonable level.

I'd probably start the search at the core and just search outwards in a straight line. It wouldn't take long, but it'd mean it'd go from O(1) to O(n) which would sadden me :3
Also, there's no way you could change from one console size to another, since it'd break the diff system as well as cause problems if you already have an existing room.

**Comment by ghost** [comment]
Yes, the door that leads to the outside dimension.  FoxPotato mentioned earlier to not place this door manually.  Just wanted to clear this up, that it had to be placed manually anyway. :-)

I've split up my design in 6 parts which should all fit together nicely.  I'll find a way to hide the boundaries so they work with the structure.  Specially for the centre piece which goes on top of the console room. (the boundary cut through a few walkways, so even when they're invisible they're still noticeable)

When creating a schema, I notice in the server console that the mod traverses the boundaries to find the outer points.  Would it perhaps be enough to have a single line in X,Y,Z, connected to the schema core? (so 4 lines in total, instead of the 16 i currently use)

The way this mod is built makes it clear a lot of thought and consideration went in to it.  The people on my server are enjoying their tardis a lot.  I was worried about performance when I first loaded the mod, but was pleasantly surprised.  Thank you!

**Comment by Soyaro666** [comment]
@DarkholmeTenk Like you mentioned having different sizes could cause trouble with existing rooms. maybe you could avoid this by locking the control room switches or restrict them to same-size rooms if a room is connected (which should be easy to find out with a little addition to your door-code I guess).
I could think of some performance problems with the same-size restriction since the Tardis had to process every shematic if you're switching them through but I guess it would be the better option. My other suggestion would cause tons of bug-reports because users can't change their console room...

**Comment by ghost** [comment]
Being restricted to the size isn't a real issue though.  Descriptive feedback when saving the schematic as a tardisConsole would be enough.  It's entirely possible to make doors float in the air to connect other rooms, thus increasing the size of the console room.
I've only noticed that the side with the outside door is very fiddly.  The white+blue door doesn't get removed, and when an attached room gets deleted, that part/room disappears as well.
Another issue I've noticed is that you need to put in the smaller parts first:
Topdown view (x = controller, o = empty, aaa = single room)
aaa
oxo
aaa
If the outside door is at an "o-side" you won't be able to place the room because there's a obstacle detected.
Doing this first solves that, but spawns above problem:
ooo
axa
ooo

But yes, it is possible to make a huge room despite the controller room having fixed dimensions.

![2015-07-25_02 25 32](https://cloud.githubusercontent.com/assets/918422/8887038/a5d8ba7a-3274-11e5-8486-b084826761b3.png)
![2015-07-25_02 25 46](https://cloud.githubusercontent.com/assets/918422/8887040/ad3e671a-3274-11e5-9cb4-b5cd4ae6b409.png)

**Comment by handicraftsman** [comment]
I don't see this bug.

**Comment by DarkholmeTenk** [comment]
Can't replicate the door problems and the original problem doesn't appear to be a real problem other than lack of verbosity in error messages :P

**Comment by handicraftsman** [comment]
)
