### ISSUE TITLE
[BUG] Transmating out of tardis in flight/landing crashes game

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#265]
sorry dark im good at finding bugs  :P

**Comment by AlienXtream** [comment]
a nice little crash report for you :)

Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.softBlock(AbstractTileEntity.java:67)
    at tardis.common.tileents.CoreTileEntity.teleportOutside(CoreTileEntity.java:546)
    at tardis.common.tileents.CoreTileEntity.transmatEntity(CoreTileEntity.java:1337)
    at tardis.common.items.SonicScrewdriverItem.func_77659_a(SonicScrewdriverItem.java:486)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
