### ISSUE TITLE
Tardis mod causing OutOfMemoryExceptions

### ISSUE THREAD

**Issue by kadamgreene** [DarkholmeTenk/TardisModIssues#268]
I am getting this:

java.lang.OutOfMemoryError: Java heap space
    at net.minecraft.nbt.NBTTagIntArray.func_152446_a(NBTTagIntArray.java:35)
    at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
    at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
    at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
    at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
    at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
    at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
    at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
    at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
    at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:34)
    at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:45)
    at com.xcompwiz.mystcraft.world.AgeController.getChunkProfiler(AgeController.java:506)
    at com.xcompwiz.mystcraft.world.AgeController.registerDebugInfo(AgeController.java:251)
    at com.xcompwiz.mystcraft.core.MystcraftEventHandler.handleWorldLoadEvent(MystcraftEventHandler.java:106)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_300_MystcraftEventHandler_handleWorldLoadEvent_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:247)
    at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
    at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorldServer(WorldHelper.java:35)
    at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorld(WorldHelper.java:27)
    at io.darkcraft.darkcore.mod.helpers.WorldHelper.getDimensionName(WorldHelper.java:61)
    at tardis.common.tileents.CoreTileEntity.writeTransmittableOnly(CoreTileEntity.java:1658)
    at io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.func_145844_m(AbstractTileEntity.java:73)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:576)
    at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)

Entering and exiting the Tardis (not every time but once or twice a day).  This is on a server with 4GB of memory allocated to Minecraft, so I don't think I'm out of memory because I can play as much as I want as long as I don't enter the tardis.

**Comment by DarkholmeTenk** [comment]
Is there any way you can do a memory profile to see where exactly memory is being used up?
Edit: I've opened an issue on the mystcraft issue tracker for it :)

**Comment by DarkholmeTenk** [comment]
See if that fixes. (DarkCore update)

**Comment by kadamgreene** [comment]
Will you be releasing the update on Curse? (I use the Curse client for managing my personal mod pack)

**Comment by DarkholmeTenk** [comment]
Eventually; does the change I made fix it?

**Comment by DarkholmeTenk** [comment]
See XCompWiz/Mystcraft-Issues#131

**Comment by kadamgreene** [comment]
As far as memory at this point:  The server is usually running around 3.5GB of memory, but when this event was triggering, it would suddenly jump to 4.5GB (hence the OOM Exception).  My server is on Minespan, so I cannot run any kind of profiler on it (and don't have enough memory on my computer to run both server and client).

**Comment by spannerman79** [comment]
> java.lang.OutOfMemoryError: Java heap space

Set `-XX:MaxPermSize=512m` in server launch if your using Java 7

I've found typical forge based servers need a min of 4GB - closer to 6GB to handle spiking.

This isn't a mod issue - more of an issue with not enough resources allocated towards the server instance.

**Comment by DarkholmeTenk** [comment]
That's permgenspace though, that's a completely unrelated block of memory used for loading classes

**Comment by DarkholmeTenk** [comment]
Assuming fixed now :)
