### ISSUE TITLE
[BUG-Minor] Crash when placing a re-named room

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#288]
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at tardis.common.blocks.InternalDoorBlock.func_149727_a(InternalDoorBlock.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by AlienXtream** [comment]
i took the sonic and set the schema to one with spaces. with the sonic in my inventory (so it doesn't update the schema) i removed the spaces so i could modify it. i tried to place the schema from the sonic (with the old name) and it crashed. suggest adding in a check something like ; if schema name not found, print to chat "Unknown File. Re-select schema on console".

**Comment by DarkholmeTenk** [comment]
This is fixed in the linking branch now.
