### ISSUE TITLE
Crash related to liquids

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#296]
One of my players apparently placed into one of the tardis liquid tanks the wrong liquid (literal explaination) and got this crash: http://pastebin.com/MBYG3qyf

"// On the bright side, I bought you a teddy bear!

Time: 15/10/15 15:17
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 10
        at tardis.common.tileents.components.ComponentFluid.fill(ComponentFluid.java:57)
        at tardis.common.tileents.components.ComponentFluid.fill(ComponentFluid.java:86)
        at tardis.common.tileents.ComponentTileEntity.fill(ComponentTileEntity.java:662)
        at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.flowFrom(LiquidConduitNetwork.java:258)
        at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.doFlow(LiquidConduitNetwork.java:129)
        at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.doTick(LiquidConduitNetwork.java:99)" etc...

The server crashes withough finishing boot up, Btw, any quick way to fix this besides backups?

**Comment by DarkholmeTenk** [comment]
Try the jenkins version; pretty sure this is already fixed

**Comment by DanNetwalker** [comment]
Ok, and if I can't release an update for some days because I'm connected through the cellular? 
House moving... _bumps head into table_ 

How can I remove the liquid tanks from a tardis whose ID I know, manually (ssh console)? In what file is that stored?

**Comment by DarkholmeTenk** [comment]
It isn't a problem with the tank, the roundel is configured to use tank 10 of (presumably) 10 which are numbered 0-9,turn on forge's remove erroring tile entities until the te causing the crash is removed

**Comment by DanNetwalker** [comment]
Oh, ok. The roundel? How can it even be configured to 10? Is is a valid bug, then? 

If not, just close the issue, since it's mine (I have to update the mod in the modpack), not yours.

Hotfixed it by restoring backup of the broken Tardis, btw.

**Comment by DarkholmeTenk** [comment]
I'm assuming you increased the number of tanks to 10, but basically I put > instead of >=
