### ISSUE TITLE
[BUG] Landing in Farmland/Wheat creates unbreakable ghost TARDIS

### ISSUE THREAD

**Issue by Tech0verlord** [DarkholmeTenk/TardisModIssues#308]
NOTE: This is on build 1.7.10-0.99-207 from the curse download page.

So I was messing around by practicing in Uncoordinated/Drift Flight mode (did end up moving somehow), my TARDIS landed in my wheat farm. While inside the TARDIS, I couldn't get out unless I moved, and using the Transmat on the SS would crash the game. After moving my TARDIS to a safe place, I managed to get out. The way I know it landed in my crops was cause when I went to them, some were trampled/crushed, and there's an invisible, two block tall structure that WAILA defines as TARDIS blocks. Only way to get rid of them was to enter creative and break em that way.

EDIT: Also, while landed in crops, and inside the TARDIS, the door says that it refuses to open for some reason.

![2015-10-26_23 32 19](https://cloud.githubusercontent.com/assets/2433224/10749337/74800374-7c3f-11e5-9b57-9c72f783edc2.png)

**Comment by AlienXtream** [comment]
try the jenkins builds of BOTH tardis AND darkcore (http://tardismod.com:8080/) and report back if you it still happens. also, the doors not opening means the tardis exterior is missing. this happens if the tardis blocks get destroyed AFTER you land (creative troll player, structure generating after landing, etc...)

**Comment by Tech0verlord** [comment]
Alright, will try them when I get home later tonight. Also, the transmat crash only happens if the "door refuses to open" message comes up and I use the transmat to go outside.

**Comment by AlienXtream** [comment]
yeh, thats been fixed a while ago i think. the curse links are rather old

**Comment by Tech0verlord** [comment]
Had some free time and tested the new versions. Ghost tardis still spawns, meaning I have to enter creative to get rid of it, and attempting to transmat out when "the door refuses to open" still crashes the game.

I'll crash it again later on today and pastebin a crashlog

**Comment by AlienXtream** [comment]
interesting... post the crash log (just in case). dose it happen while you are outsude the tardis (recall in a wheat field)?

**Comment by AlienXtream** [comment]
dark, this still occurs in the DS branch. 

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/28/15 2:37 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.softBlock(AbstractTileEntity.java:67)
    at tardis.common.tileents.CoreTileEntity.teleportOutside(CoreTileEntity.java:555)
    at tardis.common.tileents.CoreTileEntity.transmatEntity(CoreTileEntity.java:1352)
    at tardis.common.items.SonicScrewdriverItem.func_77659_a(SonicScrewdriverItem.java:284)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.softBlock(AbstractTileEntity.java:67)
    at tardis.common.tileents.CoreTileEntity.teleportOutside(CoreTileEntity.java:555)
    at tardis.common.tileents.CoreTileEntity.transmatEntity(CoreTileEntity.java:1352)
    at tardis.common.items.SonicScrewdriverItem.func_77659_a(SonicScrewdriverItem.java:284)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@4a07d2cd
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Tech0verlord** [comment]
Well, once i crash when I try to transmat out, and I load in the save, I'm back in my Tardis, those ghosts like in the pic, exist separately from the real tardis. The real tardis is actually on the other side of a nearby cliff.

EDIT: Would you prefer that I pastebin the crashlog or just paste it in here directly?
EDIT2: Just noticed you said recall the tardis into the wheat, not transmat. Will try that in a bit.

**Comment by Tech0verlord** [comment]
So, recalling the tardis into the wheat field causes a ghost tardis to appear, destrying the wheat and turning the farmland into dirt, also, no spawning sounds occur. Right clicking on any side does nothing. Hitting recall causes the ghost to remain and a real tardis spawns nearby. Seems I can transmat INTO my tardis even though it's a ghost, but attempting to transmat OUT gave me the following crashlog.

Pastebin of crashlog: http://pastebin.com/rsbKHPvG

**Comment by AlienXtream** [comment]
yeh.

**Comment by Tech0verlord** [comment]
Well, luckily I've leveled my Tardis enough that for short distance flights, it's pretty darn accurate, so I don't have to worry about landing in my wheat fields. This might become troublesome though for people who just newly acquired their own Tardis.

Let me know if there's anything else that I can do for yall.

**Comment by AlienXtream** [comment]
keep posting bugs and suggestions. though with the latter make sure they havnt already been suggested/rejected :)
