### ISSUE TITLE
[BUG] DS-booted to server list on takeoff- TEXT WALL

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#322]
[12:03:34] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel darkcore
java.lang.NullPointerException
    at tardis.common.core.flight.ShieldModifier.getValidActiveShields(ShieldModifier.java:40) ~[ShieldModifier.class:?]
    at tardis.common.core.flight.ShieldModifier.getModifiedControls(ShieldModifier.java:65) ~[ShieldModifier.class:?]
    at tardis.common.tileents.CoreTileEntity.getModifiedControls(CoreTileEntity.java:718) ~[CoreTileEntity.class:?]
    at tardis.common.tileents.CoreTileEntity.isMoving(CoreTileEntity.java:733) ~[CoreTileEntity.class:?]
    at tardis.common.tileents.CoreTileEntity.isFastLanding(CoreTileEntity.java:1093) ~[CoreTileEntity.class:?]
    at tardis.common.tileents.CoreTileEntity.takeOff(CoreTileEntity.java:802) ~[CoreTileEntity.class:?]
    at tardis.common.tileents.CoreTileEntity.takeOff(CoreTileEntity.java:836) ~[CoreTileEntity.class:?]
    at tardis.common.tileents.ConsoleTileEntity.activateControl(ConsoleTileEntity.java:599) ~[ConsoleTileEntity.class:?]
    at tardis.common.network.packet.ControlPacketHandler.handleData(ControlPacketHandler.java:42) ~[ControlPacketHandler.class:?]
    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomPacket(PacketHandler.java:42) ~[PacketHandler.class:?]
    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomServerPacket(PacketHandler.java:29) ~[PacketHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_853_PacketHandler_handleCustomServerPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by DarkholmeTenk** [comment]
Fixed
