### ISSUE TITLE
Custom room schemas from foxpotato.com

### ISSUE THREAD

**Issue by Belgabor** [DarkholmeTenk/TardisModIssues#323]
Are these no longer compatible with current Jenkins builds (including the newest on Curse)? I've not tried each and everyone, but those I did crashed me in SSP and disconnected me in SMP.

**Comment by FoxPotato** [comment]
Could you post the crash report perhaps? So we know what happened :p

**Comment by AlienXtream** [comment]
^

**Comment by DarkholmeTenk** [comment]
^ ^

**Comment by Belgabor** [comment]
Of course, just was asking quickly if it's a known thing =)

Here is the incidence on the server (yesterdays jenkins):

```
[05:56:00] [Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TETE]Control activated:73
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.IOException: Root tag must be a named compound tag
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:133)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.helpers.ServerHelper.readNBT(ServerHelper.java:55)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.core.schema.PartBlueprint.<init>(PartBlueprint.java:281)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.core.SchemaHandler.getSchema(SchemaHandler.java:217)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.core.Helper.loadSchemaDiff(Helper.java:279)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.tileents.CoreTileEntity.loadConsoleRoom(CoreTileEntity.java:996)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.tileents.EngineTileEntity.activateControl(EngineTileEntity.java:367)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at tardis.common.network.packet.ControlPacketHandler.handleData(ControlPacketHandler.java:35)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomPacket(PacketHandler.java:42)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.network.PacketHandler.handleCustomServerPacket(PacketHandler.java:29)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler_796_PacketHandler_handleCustomServerPacket_ServerCustomPacketEvent.invoke(.dynamic)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05:56:00] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[05:56:00] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@1a356277:
[05:56:00] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[05:56:00] [Server thread/ERROR] [FML/]: 0: NORMAL
[05:56:00] [Server thread/ERROR] [FML/]: 1: ASM: io.darkcraft.darkcore.mod.network.PacketHandler@28069ebd handleCustomServerPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[05:56:00] [Server thread/ERROR] [FML/]: NetworkEventFiringHandler exception
[05:56:00] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel darkcore
[05:56:00] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: Belgabor
```

Server doesn't crash, I just get kicked off when I click on the doorway to attach the new room.

Here is a crash log from a local test instance (curse version):
http://pastebin.com/6M272mwr

**Comment by FoxPotato** [comment]
Which one caused this?
and maybe try one uploaded by dark? see if that works? (if that's not this one of course)

**Comment by Belgabor** [comment]
I'm not entirely sure anymore which one each was, but Special.Eye of Harmony was one of those that has an issue. I haven't tried any of Dark's yet as those seemed like test uploads of rooms already provided by the mod itself but I can certainly do so.

**Comment by FoxPotato** [comment]
It would be lovely if you could test out a few  :)

**Comment by Belgabor** [comment]
Even Room.Library by Dark triggers it (tested on the local instance)

**Comment by Belgabor** [comment]
I now went through all, none worked.

**Comment by DarkholmeTenk** [comment]
Forge version?

**Comment by Belgabor** [comment]
Also looking at the files they seem to be different from those saved when you access the internal ones. Both of course are binary files, but the uploaded ones have readable text in them while the internal ones have not.
Forge version is 1558 locally and 1517 on the server (different pack).

**Comment by DarkholmeTenk** [comment]
Could you try with 1403? It could be that forge changed the compressed nbt data format.

**Comment by DarkholmeTenk** [comment]
http://imgur.com/PzeBIG4 I'm not seeing any difference between the downloaded one and the one in the mod.
Edit: Correction, I'm not seeing any difference when I use a download manager, when I just use chrome or firefox, it breaks stuff, let's see how to fix that.

**Comment by FoxPotato** [comment]
There is a difference between the other ones tho, like the eye of harmony one. there's readable text in there, and coordinates.

**Comment by Belgabor** [comment]
same issue with 1403

**Comment by FoxPotato** [comment]
http://prntscr.com/96eavz all three of them look like this

**Comment by Belgabor** [comment]
This is somewhat unrelated and might need a lot of work, but how about reusing the Schematica format? It has an established editor and, together with AtomicBlom's Schematic Meta-Blocks, could probably even serve for diffs of the control room or let rooms "overlap" when their bounding boxes collide but the rooms actually don't.

**Comment by AlienXtream** [comment]
they basically are schematics...

**Comment by FoxPotato** [comment]
Why fix something that should work, and probably will given some time :p

**Comment by DarkholmeTenk** [comment]
It's not a problem with the code, it's just the apache server serving the files is adding the header "content-encoding: x-gzip" which firefox/chrome take as a hint to decompress them, which is why you get plaintext data.

**Comment by DarkholmeTenk** [comment]
Should be fixed.

**Comment by Belgabor** [comment]
Awesome =)
Just one tiny thing about the page, I find it very challenging to optically figure out which "batch" of information goes together for one schema, especially once you scroll down. I was prepared to offer a css fix, but the composition of the page makes that hard if not impossible. I would suggest either a hover effect like this

``` css
div.schemaBox table tbody tr:hover { background-color:#EEEEFF }
```

(Only affecting the whole schema info) or an alternating background coloring.

**Comment by DarkholmeTenk** [comment]
See tardismod.com/schema for future versions.

**Comment by Belgabor** [comment]
Much better, thanks.
