### ISSUE TITLE
[BUG] DS-Crash on remove all rooms button

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#370]
Time: 12/13/15 7:30 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
    at tardis.common.tileents.CoreTileEntity.func_145845_h(CoreTileEntity.java:422)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
    at tardis.common.tileents.CoreTileEntity.func_145845_h(CoreTileEntity.java:422)

-- Block entity being ticked --
Details:
    Name: tile.TardisMod.TardisCore // tardis.common.tileents.CoreTileEntity
    Block type: ID #2676 (tile.TardisMod.TardisCore // tardis.common.blocks.CoreBlock)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (0,70,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #2676 (tile.TardisMod.TardisCore // tardis.common.blocks.CoreBlock)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [GCEntityPlayerMP['AlienXtream'/1308909, l='New World', x=1.52, y=68.00, z=-1.71]]
    Chunk stats: ServerChunkCache: 1089 Drop: 0
    Level seed: 2863064732228567173
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by DarkholmeTenk** [comment]
Fixed, not in a nice way, but fixed.
