### ISSUE TITLE
Crash when exiting TARDIS with DS

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#400]
Hey, first time using Tardis-DS, and with it fully damaged, I left my TARDIS, and it crashed, here's the report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/8/16 9:29 PM
Description: Getting biome

java.lang.NullPointerException: Getting biome
    at net.minecraft.world.chunk.Chunk.func_76591_a(Chunk.java:1289)
    at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:141)
    at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
    at net.minecraft.world.World.func_72807_a(World.java:130)
    at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:407)
    at net.minecraft.world.World.getSkyColorBody(World.java:1597)
    at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
    at net.minecraft.world.World.func_72833_a(World.java:1575)
    at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.world.chunk.Chunk.func_76591_a(Chunk.java:1289)

-- Coordinates of biome request --
Details:
    Location: World: (-10,0,-10), Chunk: (at 6,0,6 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
    at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:141)
    at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
    at net.minecraft.world.World.func_72807_a(World.java:130)
    at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:407)
    at net.minecraft.world.World.getSkyColorBody(World.java:1597)
    at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
    at net.minecraft.world.World.func_72833_a(World.java:1575)
    at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['InValidFire'/48, l='MpServer', x=8.50, y=66.62, z=8.50]]
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1 game time, 1 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['InValidFire'/48, l='MpServer', x=8.50, y=66.62, z=8.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 221210976 bytes (210 MB) / 373338112 bytes (356 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 7, tcache: 9, allocated: 14, tallocated: 126
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   darkcore{0.3} [Dark Core](darkcore-0.3-86.jar) 
    UCHIJAAAA   TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.1002' Renderer: 'AMD Radeon HD 8330'
    Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 8330 GL version 4.5.13399 Compatibility Profile Context 15.201.1101.1002, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by AlienXtream** [comment]
this is a biomesoplenty bug. it happens sometimes. this is NOT tardis mod related

**Comment by DarkholmeTenk** [comment]
Yeah, this is definitely a world generation bug, definitely not tardis mod related, from what I can see.
