### ISSUE TITLE
Crash Report - Mod Not Loading

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#402]
Hi, while I was updating my modpack to include the latest version of the DS, I experienced a crash during load, I don't know if this is an incompatibility or what... please help.

---

---- Minecraft Crash Report ----
// My bad.

Time: 1/11/16 7:29 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: io/darkcraft/darkcore/mod/datastore/HashMapSet
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: io/darkcraft/darkcore/mod/datastore/HashMapSet
    at tardis.common.core.flight.ShieldModifier.<clinit>(ShieldModifier.java:21)
    at tardis.common.core.flight.FlightConfiguration.<clinit>(FlightConfiguration.java:28)
    at tardis.TardisMod.refreshConfigs(TardisMod.java:211)
    at tardis.TardisMod.preInit(TardisMod.java:185)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: io.darkcraft.darkcore.mod.datastore.HashMapSet
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1494889600 bytes (1425 MB) / 2032140288 bytes (1938 MB) up to 2032140288 bytes (1938 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 Optifine OptiFine_1.7.10_HD_U_C1 51 mods loaded, 51 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](modpack.jar) 
    UCH Forge{10.13.4.1566} [Minecraft Forge](modpack.jar) 
    UCH AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH RenderPlayerAPI{1.0} [Render Player API](minecraft.jar) 
    UCH ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4 %281%29.jar) 
    UCH arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008 %281%29.jar) 
    UCH antiqueatlas{4.2.7-1.7.10} [Antique Atlas](antiqueatlas-4.2.7-1.7.10.jar) 
    UCH CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCH AntMan{Beta-1.7.10-1.4.0} [AntMan](AntMan-Beta-1.7.10-1.4.0.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH betterstorage{0.13.1.127} [BetterStorage](BetterStorage-1.7.10-0.13.1.127.jar) 
    UCH BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCH TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCH chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCH craftguide{1.6.8.2} [CraftGuide](CraftGuide-1.6.8.2-forge.jar) 
    UCH darkcore{0.3} [Dark Core](darkcore-0.3-45.jar) 
    UCH DragonsRadioMod{1.7.1} [Dragon's Radio Mod](Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
    UCH DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) 
    UCH EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCH ForgeEssentials{1.4.3} [Forge Essentials](forgeessentials-1.7.10-1.4.3.1021-server.jar) 
    UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.375.jar) 
    UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.375.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCH HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCH NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCH Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCH Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCH foxlib{1.7.10-0.7.0} [FoxLib](FoxLib-1.7.10-0.7.0.jar) 
    UCH Tails{1.7.10-1.4.1a} [Tails](Tails-1.7.10-1.4.1a.jar) 
    UCE TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCH ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCH vending{1.2.3} [vending](vending-v1.2.3.jar) 
    UCH witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCH XaeroMinimap{1.7.3.1} [Xaero's Minimap](xaeros_minimap_v1.7.3.1_Forge_1.7.10.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.1002' Renderer: 'AMD Radeon HD 8330'
    CoFHCore: -[1.7.10]3.0.2-262
    ForgeEssentials: Running ForgeEssentials 1.4.3.1021 (b38ffbe). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WorldBorder, factions, mapper
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    NetherOres: -[1.7.10]2.3.0-12
    TConstruct Environment: Environment healthy.

**Comment by Validfire** [comment]
Fixed the problem, not correct DarkCore version, then had some issues with ThaumicTinkerers, which I had to remove... However it's working now.
