### ISSUE TITLE
Multiplayer: Roundels with ME Cable Interface require reboot to become functional

### ISSUE THREAD

**Issue by Entoarox** [DarkholmeTenk/TardisModIssues#413]
As said in the title, ME Cable Interfaces do not work until the server has been rebooted
This is a rather annoying issue, since it makes it rather difficult to modify the cabling for my tardis.

**Comment by ghost** [comment]
I am using Forge core and didn't have same problem. What core you use?

**Comment by Entoarox** [comment]
Pure forge, and its literally just the ME cable interfaces, the other ones function properly pretty much from the moment I put them down.

**Comment by ghost** [comment]
I have no problems, maybe you are using beta or even alpha release of AE2?

**Comment by Entoarox** [comment]
I am using the latest RV2 release, not one of the beta's, further, keep in mind this is _multiplayer_ and not single-player...

**Comment by ghost** [comment]
Have you tried without other mods? Idk, i'm playing multiplayer and don't have same problem...

**Comment by Entoarox** [comment]
And what mod would interfere with the roundels in such a way that they cannot update when the ME upgrade is applied? Because everything else works perfectly with both the Tardis and AE, it is literally this singular interaction that fails.

**Comment by DarkholmeTenk** [comment]
I have not seen this behaviour. Have you tried triggering a block update or breaking/placing the cable or anything?
Other than that, pastebin your mod list and console output when you place a cable/etc pls :)

**Comment by Entoarox** [comment]
Block update has absolutely no effect, the console output from the moment I place the upgrade till after the cable is placed:

```
01:23:18  [Info] [STDOUT]: [tardis.common.items.SonicScrewdriverItem:rightClickBlock:232]: T
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.FailedConnection
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridConnection.<init>(GridConnection.java:70)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.core.Api.createGridConnection(Api.java:132)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.addConnection(ComponentGrid.java:194)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.linkToCore(ComponentGrid.java:145)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:160)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.getGridNode(ComponentGrid.java:120)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.ComponentTileEntity.getGridNode(ComponentTileEntity.java:797)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode.FindConnections(GridNode.java:406)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode.updateState(GridNode.java:217)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_703_TickHandler_onTick_TickEvent.invoke(.dynamic)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at fastcraft.W.a(F:644)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at fastcraft.H.aq(F:51)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
01:23:42  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by DarkholmeTenk** [comment]
I'm gonna say try without fastcraft

**Comment by Entoarox** [comment]
Restarted the server without fastcraft, the same issue occurs still:

```
02:41:18  [Info] [STDOUT]: [tardis.common.items.SonicScrewdriverItem:rightClickBlock:232]: T
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.FailedConnection
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridConnection.<init>(GridConnection.java:70)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.core.Api.createGridConnection(Api.java:132)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.addConnection(ComponentGrid.java:194)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.linkToCore(ComponentGrid.java:145)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:160)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.revive(ComponentGrid.java:101)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.ComponentTileEntity.reviveComps(ComponentTileEntity.java:143)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.ComponentTileEntity.init(ComponentTileEntity.java:172)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:186)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.world.World.func_72939_s(World.java:1939)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
02:41:21  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
02:41:21  [Info] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Adding coord:World 15:-27,70,2
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.FailedConnection
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridConnection.<init>(GridConnection.java:70)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.core.Api.createGridConnection(Api.java:132)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.addConnection(ComponentGrid.java:194)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.linkToCore(ComponentGrid.java:145)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:160)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.components.ComponentGrid.getGridNode(ComponentGrid.java:120)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at tardis.common.tileents.ComponentTileEntity.getGridNode(ComponentTileEntity.java:797)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode.FindConnections(GridNode.java:406)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode.updateState(GridNode.java:217)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_699_TickHandler_onTick_TickEvent.invoke(.dynamic)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
02:41:24  [Info] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Webber88** [comment]
was this the first thing on the crash popup(you know the eroor screen when you crash)?

**Comment by Entoarox** [comment]
Nothing crashes, the server functions perfectly fine, the ME cable and anything attached simply wont work untill the server is restarted.

Edit: The log data is from when I right-click the roundel with the screwdriver (The T message) untill after the STRERR ended, and the only content in the log after that was a few 'cant keep up' messages

**Comment by ImDoctorChaos** [comment]
@Entoarox Were having two different AE issues. My roundels work until you reboot then they all link together.

**Comment by Entoarox** [comment]
If it helps any in debugging this, the issue does not occur in a SSP world, only the SMP world.

**Comment by Entoarox** [comment]
Another "if it helps": It looks like I cant connect more then 30 channels to the roundels, not even as direct connections. as far as AE is concerned roundels have a global 30 channel limit even when those roundels are supposed to be connected directly to eachother.

**Comment by DarkholmeTenk** [comment]
I'm assuming you have a security terminal. Try adding default build permissions to it (i.e. give build permissions to a blank biometric thingum) and see if that fixes.
