### ISSUE TITLE
[BUG] Crash on auto fill names with /ttp

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#418]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/25/16 2:24 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
    at io.darkcraft.darkcore.mod.abstracts.AbstractCommandNew.getPlayerList(AbstractCommandNew.java:117)
    at io.darkcraft.darkcore.mod.abstracts.AbstractCommandNew.func_71516_a(AbstractCommandNew.java:124)
    at tardis.common.command.TeleportCommand.func_71516_a(TeleportCommand.java:51)
    at net.minecraft.command.CommandHandler.func_71558_b(CommandHandler.java:202)
    at net.minecraft.server.MinecraftServer.func_71248_a(MinecraftServer.java:793)
    at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1050)
    at net.minecraft.network.play.client.C14PacketTabComplete.func_148833_a(SourceFile:31)
    at net.minecraft.network.play.client.C14PacketTabComplete.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 17 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 794764568 bytes (757 MB) / 1125072896 bytes (1072 MB) up to 6335102976 bytes (6041 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   darkcore{0.3} [Dark Core](darkcore-0.3-99.jar) 
    UCHIJAAAA   TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-142-DS.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['AlienXtream'/280, l='New World', x=10.44, y=70.11, z=0.90]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DarkholmeTenk** [comment]
Whoops. Eclipse imported the scala Arrays class instead of the java one.

**Comment by AlienXtream** [comment]
_facepalm_
