### ISSUE TITLE
[BUG] Remove function on magic door crashes client AND corrupts save

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#437]
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at tardis.common.tileents.SchemaCoreTileEntity.repairRow(SchemaCoreTileEntity.java:345)
    at tardis.common.tileents.SchemaCoreTileEntity.repairDoor(SchemaCoreTileEntity.java:378)
    at tardis.common.tileents.SchemaCoreTileEntity.recheckDoors(SchemaCoreTileEntity.java:304)
    at tardis.common.tileents.CoreTileEntity.refreshDoors(CoreTileEntity.java:1232)
    at tardis.common.tileents.MagicDoorTileEntity.recheckDoors(MagicDoorTileEntity.java:161)
    at tardis.common.tileents.MagicDoorTileEntity.screw(MagicDoorTileEntity.java:208)
    at tardis.common.items.SonicScrewdriverItem.screwScrewable(SonicScrewdriverItem.java:168)
    at tardis.common.items.SonicScrewdriverItem.handleBlock(SonicScrewdriverItem.java:218)
    at tardis.common.blocks.AbstractScrewableBlockContainer.func_149727_a(AbstractScrewableBlockContainer.java:32)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by FoxPotato** [comment]
Maybe some more info, I am unable to recreate this bug.

**Comment by AlienXtream** [comment]
Will recreate the bug and post all relevant info tomorrow.

**Comment by DarkholmeTenk** [comment]
You deleted the schema file?

**Comment by AlienXtream** [comment]
No but wil renaming id have the same effect? Cos i renamed the schema to spawn it in

**Comment by AlienXtream** [comment]
yeh, renaming the schema file back to its original name worked. perhaps add in a thing where using an underscore will search for a space OR an underscore?
