### ISSUE TITLE
[BUG] AE2 roundel interface derpiness

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#452]
1. something odd ive noticed is that the ME roundels appear not to update the network in all scenarios. smart/dense cables showing incorrect usage.
   1. favoring 8 channel networks sometimes (not enough channels even when there is in theory). 
2. devices not coming online until i reload the game entirely to clear the cache. 

1 & 3 are really one in the same and 2 is solved by only using dense cable for controller outputs

**Comment by AlienXtream** [comment]
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.FailedConnection
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at appeng.me.GridConnection.<init>(GridConnection.java:70)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at appeng.core.Api.createGridConnection(Api.java:132)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.addConnection(ComponentGrid.java:194)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.linkToCore(ComponentGrid.java:145)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:160)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.revive(ComponentGrid.java:101)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.reviveComps(ComponentTileEntity.java:143)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.init(ComponentTileEntity.java:172)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:186)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[18:40:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[18:40:01] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Adding coord:World 3:-4,69,11
[18:40:01] [Client thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Adding coord:World 3:-4,69,11

**Comment by AlienXtream** [comment]
console output from rv3

[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.SecurityConnectionException: Connection failed due to different security realms.
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at appeng.me.GridConnection.<init>(GridConnection.java:75)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at appeng.core.Api.createGridConnection(Api.java:132)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.addConnection(ComponentGrid.java:194)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.linkToCore(ComponentGrid.java:145)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:160)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.components.ComponentGrid.revive(ComponentGrid.java:101)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.reviveComps(ComponentTileEntity.java:143)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.init(ComponentTileEntity.java:172)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:186)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[18:59:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[18:59:33] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Adding coord:World 3:-16,49,21
[18:59:34] [Client thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Adding coord:World 3:-16,49,21

**Comment by AlienXtream** [comment]
this issue is caused when the network has a security terminal on it. the tardis basically dosn't have permission to modify the network. to resolve this create a blank biometric card and give it permission to build on the network. this will allow the tardis permission to edit the network
