### ISSUE TITLE
[BUG] ANOTHER crash on rightclicking colorable blocks

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#454]
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at tardis.common.blocks.ColorableBlock.getIterator(ColorableBlock.java:61)
    at tardis.common.blocks.ColorableBlock.getColoringIterator(ColorableBlock.java:71)
    at io.darkcraft.darkcore.mod.abstracts.AbstractBlock.func_149727_a(AbstractBlock.java:469)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at tardis.common.blocks.ColorableBlock.getIterator(ColorableBlock.java:61)
    at tardis.common.blocks.ColorableBlock.getColoringIterator(ColorableBlock.java:71)
    at io.darkcraft.darkcore.mod.abstracts.AbstractBlock.func_149727_a(AbstractBlock.java:469)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

just started happening out of no where without an apparent cause :/

**Comment by AlienXtream** [comment]
appears to only affect the blocks in a specific area of my tardis

**Comment by DarkholmeTenk** [comment]
Far enough away from the cte that it doesn't exist clientside I imagine

**Comment by AlienXtream** [comment]
it is far out from the console room yes. probably wana stop that somehow
