### ISSUE TITLE
StackOverflowError since update

### ISSUE THREAD

**Issue by Sir-Will** [DarkholmeTenk/TardisModIssues#528]
Updated from 1.7.10-0.994-290 to 1.7.10-0.995-350 (nothing else got updated except tardis and darkcore) and now I'm getting this crash frequently:

```
java.lang.StackOverflowError: Ticking block entity
    at tardis.common.tileents.ComponentTileEntity.func_70301_a(ComponentTileEntity.java:594)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:131)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:163)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:163)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:163)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at tardis.common.tileents.ComponentTileEntity.func_70301_a(ComponentTileEntity.java:594)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:131)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:163)
    at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleExtraction.tryExtraction(RelocatorModuleExtraction.java:163)
-- Block entity being ticked --
Details:
    Name: relocator // com.dynious.refinedrelocation.tileentity.TileRelocator
    Block type: ID #1153 (tile.relocator // com.dynious.refinedrelocation.block.BlockRelocator)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-64,89,3), Chunk: (at 0,5,3 in -4,0; contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #1153 (tile.relocator // com.dynious.refinedrelocation.block.BlockRelocator)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2520)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)

-- Affected level --
Details:
    Level name: tardis/DIM2737
    All players: 1 total; [GCEntityPlayerMP['Peter_Bohus'/11615, l='tardis/DIM2737', x=-3.63, y=71.49, z=39.01](Peter_Bohus at -3.6293456589574786,71.49459466512586,39.01480032349075)]
    Chunk stats: ServerChunkCache: 101 Drop: 0
    Level seed: 4350153571568782597
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (9,64,-503), Chunk: (at 9,4,9 in 0,-32; contains blocks 0,0,-512 to 15,255,-497), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 101121382 game time, 101121382 day time
    Level dimension: 2737
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 20212 (now: false), thunder time: 87316 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
```

**Comment by DarkholmeTenk** [comment]
This doesn't make much sense. Could you post the full log to pastebin and put a link pls. As far as I can see this is a refined relocation bug.

**Comment by DarkholmeTenk** [comment]
Closing due to lack of new info.
