### ISSUE TITLE
Compatibility Issue?

### ISSUE THREAD

**Issue by AlyMagica** [DarkholmeTenk/TardisModIssues#548]
I've been compiling a modpack and I'd like to include the TARDIS mod, but I think there's a compatibility issue because I've tried a few different releases of the mod and I've gotten the same crash report each time. The crash occurs before the mods finish initializing, and it doesn't crash at all when I remove the mod. I'll list the mods I'm trying to add below, followed by a copy of the crash report.

Applied Energistics 2
Big Reactors
Blood Magic
Botania
Ender IO
Equivalent Exchange 3
Extra Utilities
Forbidden Magic
Not Enough Items
Portal Gun
Random Things
Sync
Tainted Magic
TARDIS
Thaumcraft
Thaumic Infusion
Thaumic Tinkerer
Thermal Expansion
Waila
Waila Harvestability

Crash Report:
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: io.darkcraft.darkcore.mod.network.PacketHandler.registerHandler(ILio/darkcraft/darkcore/mod/interfaces/IDataPacketHandler;)Z
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: io.darkcraft.darkcore.mod.network.PacketHandler.registerHandler(ILio/darkcraft/darkcore/mod/interfaces/IDataPacketHandler;)Z
    at tardis.common.network.TardisPacketHandler.registerHandlers(TardisPacketHandler.java:20)
    at tardis.TardisMod.doingInit(TardisMod.java:268)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 130924320 bytes (124 MB) / 463630336 bytes (442 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 42 mods loaded, 42 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHI    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCHI    CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.1-237.jar) 
    UCHI    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHI    AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHI    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHI    Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHI    darkcore{0.41} [Dark Core](darkcore-0.41-179.jar) 
    UCHI    endercore{1.7.10-0.2.0.36_beta} [EnderCore](EnderCore-1.7.10-0.2.0.36_beta.jar) 
    UCHI    EE3{0.3.0.547} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.0.547.jar) 
    UCHI    ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHI    ForbiddenMagic{1.7.10-0.575} [Forbidden Magic](Forbidden Magic-1.7.10-0.575.jar) 
    UCHI    iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHI    NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHI    PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCHI    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHI    Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCHI    TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHE    TardisMod{0.99} [Tardis Mod](tardismod-1.7.10-0.99-207.jar) 
    UCHI    thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHI    thaumicinfusion{4.32} [Thaumic Infusion](ThaumicInfusion-4.32.jar) 
    UCHI    WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHI    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.4-114
    ThermalExpansion: -[1.7.10]4.1.1-237
Witchery

**Comment by DarkholmeTenk** [comment]
Invalid darkcore version for that TM version from the look of it. Check curseforge (project site vs actual curse) or the jenkins

**Comment by AlyMagica** [comment]
Thank you for the help, sorry to waste your time with what was apparently a really simple issue. And thank you for the quick answer, I was ready to play the pack without that mod until I got a reply.
