### ISSUE TITLE
Crashes because of mod Incompatability (probably)

### ISSUE THREAD

**Issue by NuclearFart** [DarkholmeTenk/TardisModIssues#551]
mod incompatibility, I think. DragonAPI, Rotarycraft, Reactorcraft upsetting TM's AE2 API
Crash Log:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/4/16 11:53 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
    at tardis.TardisMod.postInit(TardisMod.java:263)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    ... 10 more
Caused by: appeng.api.exceptions.CoreInaccessibleException: AE2 API tried to access the appeng.core.Api class, without it being declared.
    at appeng.api.AEApi.<clinit>(AEApi.java:56)
    ... 37 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 164288880 bytes (156 MB) / 526573568 bytes (502 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D3 51 mods loaded, 51 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJ   ivtoolkit{IvToolkit} [1.1](minecraft.jar) 
    UCHIJ   PlayerAPI{1.4} [Player API](minecraft.jar) 
    UCHIJ   RenderPlayerAPI{1.0} [Render Player API](minecraft.jar) 
    UCHIJ   TooManyItems{1.7.10} [TooManyItems](minecraft.jar) 
    UCHIJ   <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJ   psychedelicraftcore{1.4} [Psychedelicraft Core](minecraft.jar) 
    UCHIJ   FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHIJ   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
    UCHIJ   DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJ   BuildCraft|Core{7.1.17} [BuildCraft](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Silicon{7.1.17} [BC Silicon](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Transport{7.1.17} [BC Transport](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Builders{7.1.17} [BC Builders](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Energy{7.1.17} [BC Energy](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Robotics{7.1.17} [BC Robotics](buildcraft-7.1.17.jar) 
    UCHIJ   BuildCraft|Factory{7.1.17} [BC Factory](buildcraft-7.1.17.jar) 
    UCHIJ   climatecontrol{0.6.beta57} [Climate Control](ClimateControl-0.6.beta59.jar) 
    UCHIJ   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d%2821feb16%29.jar) 
    UCHIJ   darkcore{0.25} [Dark Core](darkcore-0.25-35.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V15a.jar) 
    UCHIJ   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJ   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   Mekanism{9.1.0} [Mekanism](Mekanism-1.7.10-9.1.0.281.jar) 
    UCHIJ   MekanismGenerators{9.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.1.0.281.jar) 
    UCHIJ   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJ   MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCHIJ   NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) 
    UCHIJ   PetBat{1.3.6} [Pet Bat](PetBat-1.7.10.jar) 
    UCHIJ   psychedelicraft{1.5.2} [Psychedelicraft](Psychedelicraft-1.5.2.jar) 
    UCHIJ   qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.69-universal.jar) 
    UCHIJ   RotaryCraft{1.0} [RotaryCraft](RotaryCraft 1.7.10 V15a %281%29.jar) 
    UCHIJ   ReactorCraft{1.0} [ReactorCraft](ReactorCraft 1.7.10 V15a.jar) 
    UCHIJ   ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJ   rivalrebels{1.7.10U} [Rival Rebels](rivalrebels-1.7.10U.jar) 
    UCHIE   TardisMod{0.985} [Tardis Mod](tardismod-1.7.10-0.985-178.jar) 
    UCHIJ   weatherManMod{RELEASE} [Weather Carpets](Weather Carpets Mod-1.2.5.jar) 
    UCHIJ   worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
    UCHIJ   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJ   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJ   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJ   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJ   MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
    UCHIJ   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    OptiFine Version: OptiFine_1.7.10_HD_U_D3
    Render Distance Chunks: 12
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.0
    OpenGlRenderer: AMD Radeon HD 7340 Gr

**Comment by LizzyTrickster** [comment]
Crashlog? Mod versions? Anything that might actually help Dark and Co. fix the issue?

**Comment by DarkholmeTenk** [comment]
Yeah, this needs a lot more info, e.g.
When does this crash happen? On boot? on loading world? etc?
Is this a crash where you don't have AE2 and there's a problem in TM? Is it in TM's implementation of the AE2 api?
Is it reproducible? Are you using the latest versions of TM and DC?
Post a crash report and give as much useful information as you can, please.

**Comment by NuclearFart** [comment]
it was very reproducible at the time it happened every time I tried loading
the game. Well I found out that it may be a mod incompatibility, but
I don't know  anything about programming language. it works just fine
without Reika mods (dragonAPI, Rotarycraft, etc.) AE2, not the mod, the API in the TARDIS mod.

**Comment by AlienXtream** [comment]
reika's mods don't play nice with many other mods out there im sad to say :(

**Comment by NuclearFart** [comment]
yea reika's mods play nice with VERY few mods, and may or may not cause lag
spikes.

**Comment by addrever** [comment]
I am getting an issue between Chromaticraft v15a and tardismod 0.995-355 with darkcore 0.41 I believe.  On the side client seems to load without issue.  It's only when I bust out a server.

Attached is the crash log.
[crash-2016-08-18_02.08.41-server.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/424266/crash-2016-08-18_02.08.41-server.txt)

It happens as the mods are being loaded.  I forget which stage.

I should also mention I'm using DragonAPI v15a, Chromaticraft v15a and forge 1566 for 1.7.10.

Thanks for your time and if I can answer any other questions I'd be happy to.

Thanks,
Savos

**Comment by AlienXtream** [comment]
reika's mods are NOT supported by TM. if you get them working with it good for you but very little/no support will be provided on the part of Tardis mod. i would suggest either bug reika or visit the tardis mod MCF page and ask the community for help.

**Comment by addrever** [comment]
Thanks.

**Comment by AlienXtream** [comment]
Hey, sorry. I didn't mean to come across as hostile. Its just that reika's mods, while cool, are like oil and water. It is possible to get them to work with other mods but they are so sensitive that its problematic. Think of them as that guy at a party who barges in and turns it into a mess. Some people will just roll with it, others won't so easily. Dark suspects that reika is doing stuff to change/break forge code (messes with the party) and causes scenarios that break alot of stuff that depends on it (its like the cops getting called and breaking up the party). Bottom line... Not darks problem :p

**Comment by AlienXtream** [comment]
At least thats how i understand it

**Comment by addrever** [comment]
No worries.  Thanks for looking into it.

**Comment by DarkholmeTenk** [comment]
So reika's mods break some forge code related to removing APIs from mods when they aren't installed. Reika blames Forge, this is nothing related to TM.

**Comment by savosdarkran** [comment]
Appreciate the follow up.
