### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Mohl97** [DarkholmeTenk/TardisModIssues#574]
Me and my friend are trying to get a little 2 person server running, but for some reason the newest version (.995 -356) of the tardis mod crashes on my friend's server. It works totally fine on my client, and .994 works fine on the server (aside from crashing whenever we start uncoordinated flight, as was fixed by 995), but we have no idea why it's crashing.

Edit: Just confirmed that it works fine on both my client and my friend's client. Just not server-side.

Edit 2: Just tested, .995 -355 works fine on the server as well.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11/15/16 10:07 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: io/darkcraft/darkcore/mod/abstracts/AbstractBlockRenderer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: io/darkcraft/darkcore/mod/abstracts/AbstractBlockRenderer
	at tardis.TardisMod.initBlocks(TardisMod.java:298)
	at tardis.TardisMod.preInit(TardisMod.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: io.darkcraft.darkcore.mod.abstracts.AbstractBlockRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4662070920 bytes (4446 MB) / 4996988928 bytes (4765 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xms3g -Xmx8g
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCH	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCH	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCH	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCH	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCH	Pistronics2{0.6.3} [Pistronics 2] (1.7.10-Pistronics2-v0.6.4.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCH	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCH	AppleCore{1.3.1} [AppleCore] (AppleCore-mc1.7.10-1.3.1.jar) 
	UCH	Avaritia{1.11} [Avaritia] (Avaritia-1.11.jar) 
	UCH	BattleTowers{1.5.2} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCH	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCH	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCH	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCH	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UCH	darkcore{0.45} [Dark Core] (darkcore-0.45-224.jar) 
	UCH	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCH	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46.jar) 
	UCH	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCH	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCH	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCH	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCH	grapplemod{1.7.10-v8} [Grappling hook mod] (grapplemod-1.7.10-v8.jar) 
	UCH	guideapi{1.7.10-1.0.1-29} [Guide-API] (Guide-API-1.7.10-1.0.1-29.jar) 
	UCH	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCH	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCH	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCH	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	ShetiPhianCore{3.0.0} [ShetiPhian-Core] (ShetiPhianCore-1.7.10-3.0.0.jar) 
	UCH	platforms{0.1.2} [Platforms] (platforms-1.7.10-0.1.2.jar) 
	UCH	ProjectE{1.7.10-PE1.10.0} [ProjectE] (ProjectE-1.7.10-PE1.10.0.jar) 
	UCH	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCH	RedLogic{59.1.13} [RedLogic] (redlogic-59.1.13.jar) 
	UCH	libsandstone{1.0.0} [libsandstone] (Reliquary-1.7.10-1.2.1.483.jar) 
	UCH	xreliquary{1.2} [Reliquary] (Reliquary-1.7.10-1.2.1.483.jar) 
	UCH	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCH	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCH	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCH	flammpfeil.smartmovingfix{1.7.x-r2alpha3} [flammpfeil.smartmovingfix] (SmartMovingFix-1.7.x-r2alpha3.jar) 
	UCH	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCE	TardisMod{0.995} [Tardis Mod] (tardismod-1.7.10-0.995-356.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCH	TiConAutoToolStation{1.1.2} [Tinkers Construct Auto Tool Station] (TiConAutoToolStation-1.7.10-1.1.2.jar) 
	UCH	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCH	Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
	UCH	Tubestuff{59.0.4} [Tubestuff] (tubestuff-59.0.4.jar) 
	UCH	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCH	VeinMiner{0.34.1_1.7.10-4d066f1} [Vein Miner] (VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.7.10-4d066f1} [Mod Support] (VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCH	ae2wct{1.7.10-rv2-1.8.7b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv2-1.8.7b.jar) 
	UCH	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCH	WR-CBE|Core{1.4.1.11} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	WR-CBE|Addons{1.4.1.11} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	WR-CBE|Logic{1.4.1.11} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	ZAMod{v1.10} [Zombie Awareness] (zombieawareness-1.7.10-1.10.jar) 
	UCH	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	Mantle Environment: Environment healthy.
	ThermalExpansion: -[1.7.10]4.1.4-247
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* ae2wct|API (1.7.10-rv3-1.8.6b) from WirelessCraftingTerminal-1.7.10-rv2-1.8.7b.jar
		* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.1.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.5-115.jar
		* BotaniaAPI (61) from Avaritia-1.11.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|energy (1.7.10R1.0.13) from ImmersiveEngineering-0.7.7.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|item (1.7.10R1.0.13) from ImmersiveEngineering-0.7.7.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* ComputerCraft|API (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|FileSystem (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Lua (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Media (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Peripheral (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Permissions (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Redstone (1.75) from tardismod-1.7.10-0.995-356.jar
		* ComputerCraft|API|Turtle (1.75) from tardismod-1.7.10-0.995-356.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* Guide-API|API (1.7.10-1.0.1-29) from Guide-API-1.7.10-1.0.1-29.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.7.7.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1.jar
		* ProjectEAPI (7) from ProjectE-1.7.10-PE1.10.0.jar
		* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.7.7.jar
		* Thaumcraft|API (4.2.2.0) from Pam's HarvestCraft 1.7.10Lb.jar
		* VeinMinerApi (0.3) from VeinMiner-0.34.1-1.7.10r473+4d066f1.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from ImmersiveEngineering-0.7.7.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by FoxPotato** [comment]
Do you have the latest version of darkcore?

**Comment by Mohl97** [comment]
Yeah, we both had the latest version of darkcore, according to the Jenkins. 0.45 -224.

**Comment by mirrormagic1** [comment]
I have the same issue.

**Comment by mirrorfagic** [comment]
Hey Actually Try removing immersive engineering to see if that fixes the problem, It may or may not work but its worth a try.

**Comment by shadowbolt79** [comment]
#589 seems to be the same error as this
