### ISSUE TITLE
[CRASH] Null pointer on invalid/unknown world handler *TEXT WALL*

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#628]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorldID(WorldHelper.java:79)
	at io.darkcraft.darkcore.mod.datastore.SimpleCoordStore.<init>(SimpleCoordStore.java:42)
	at tardis.common.tileents.CoreTileEntity.placeBox(CoreTileEntity.java:932)
	at tardis.common.tileents.CoreTileEntity.nextFlightState(CoreTileEntity.java:247)
	at tardis.common.tileents.CoreTileEntity.flightTick(CoreTileEntity.java:301)
	at tardis.common.tileents.CoreTileEntity.func_145845_h(CoreTileEntity.java:399)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorldID(WorldHelper.java:79)
	at io.darkcraft.darkcore.mod.datastore.SimpleCoordStore.<init>(SimpleCoordStore.java:42)
	at tardis.common.tileents.CoreTileEntity.placeBox(CoreTileEntity.java:932)
	at tardis.common.tileents.CoreTileEntity.nextFlightState(CoreTileEntity.java:247)
	at tardis.common.tileents.CoreTileEntity.flightTick(CoreTileEntity.java:301)
	at tardis.common.tileents.CoreTileEntity.func_145845_h(CoreTileEntity.java:399)

-- Block entity being ticked --
Details:
	Name: tile.TardisMod.TardisCore // tardis.common.tileents.CoreTileEntity
	Block type: ID #3587 (tile.TardisMod.TardisCore // tardis.common.blocks.CoreBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (0,70,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #3587 (tile.TardisMod.TardisCore // tardis.common.blocks.CoreBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Alien's World
	All players: 1 total; [GCEntityPlayerMP['AlienXtream'/3029, l='Alien's World', x=-1.42, y=68.00, z=0.04]]
	Chunk stats: ServerChunkCache: 709 Drop: 0
	Level seed: 5048538520515793538
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by AlienXtream** [comment]
perhaps have a way to catch invalid world handlers and trigger a "failed to launch" with a sound similar to the Dr who episode "curse of the black spot" where the tardis couldnt find a valid plane. idk if that sorta thing is even possible to detect before it crashes though
